wandb: {}
project_name: mixed2
restore_ckpt: ./checkpoints/mixed-492000.pth
# restore_ckpt: "/data2/cjd/mono_fusion/checkpoints/sceneflow.pth"
logdir: './checkpoints/mixed2/'
encoder: 'vitl'
batch_size: 1
gradient_accumulation_steps: 2
train_datasets: ['mixed']
lr: 1e-5
wdecay: 1e-5
total_step: 200000
save_frequency: 2000
save_path: './checkpoints/mixed2/'
val_frequency: 2000
# image_size: [352, 896]
image_size: [480, 640]
# image_size: [608, 800]
train_iters: 20
valid_iters: 32
val_dataset: 'kitti'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
# max_disp: 768
max_disp: 576
saturation_range: [0.0, 1.4]
do_flip: True
spatial_scale: [-0.2, 0.4]
noyjitter: False
num_gpu: 1
seed: 666
