wandb: {}
project_name: mixed_vggt_2
restore_ckpt: ./checkpoints/mixed_vggt/final.pth
logdir: './checkpoints/mixed_vggt_2/'
encoder: 'vits'
batch_size: 2
gradient_accumulation_steps: 1
train_datasets: ['mixed']
lr: 4e-6
# lr: 2e-3
wdecay: 1e-5
total_step: 200000
save_frequency: 100
save_path: ./checkpoints/mixed_vggt_2/
val_frequency: 100
image_size: [518, 518]
train_iters: 22
valid_iters: 32
val_dataset: 'kitti'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 630
saturation_range: [0.7, 1.3]
do_flip: True
spatial_scale: [-0.2, 0.5]
noyjitter: False
num_gpu: 1
# seed: 666
seed: 777
